version: "2"

services:
  nginx:
    image: chainify/app-nginx
    container_name: app-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - api
      - parser
      - ipfs
    restart: always

  web:
    image: chainify/app-web
    container_name: app-web
    depends_on:
      - api
    restart: always
    command: bash -c "npm run start"

  api:
    image: chainify/engine-api
    container_name: engine-api
    depends_on:
      - ipfs
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    restart: always

  parser:
    image: chainify/engine-parser
    container_name: engine-parser
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    labels:
      - "autoheal=true"
    restart: always

  ipfs:
    image: chainify/engine-ipfs
    container_name: engine-ipfs
    volumes:
      - ~/.data/ipfs/chainify:/data/ipfs
    tty: true
    stdin_open: true
    restart: always

  autoheal:
    image: chainify/engine-autoheal
    container_name: engine-autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal