version: "2"

services:
  nginx:
    image: chainify/nolik-nginx
    container_name: nolik-nginx
    ports:
      - 80:80
      - 443:443
      - 4001:4001
      - 5001:5001
    depends_on:
      - web
      - api
      - parser
      - ipfs
    restart: always

  web:
    image: chainify/nolik-web
    container_name: nolik-web
    depends_on:
      - api
    restart: always
    command: bash -c "npm run start"

  api:
    image: chainify/engine-api
    container_name: engine-api
    depends_on:
      - ipfs
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    restart: always

  parser:
    image: chainify/engine-parser
    container_name: engine-parser
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    labels:
      - "autoheal=true"
    restart: always

  ipfs:
    image: chainify/engine-ipfs
    container_name: engine-ipfs
    volumes:
      - ~/.data/ipfs/chainify/data:/data/ipfs
      - ~/.data/ipfs/chainify/staging:/export
    tty: true
    stdin_open: true
    restart: always

  autoheal:
    image: chainify/engine-autoheal
    container_name: engine-autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal